### ISSUE TITLE
wallet not ok

### ISSUE THREAD

**Issue by saigoncoin** [polymorpher/one-wallet#104] opened 2021-09-02 06:04 UTC
It's really hard to use your wallet, it's unusual and there's no careful instruction, if the end user like me doesn't understand it means you're on the wrong track and can't develop. Many inventors have They are considered crazy when they come up with inventions and ideas that cannot be understood at the time, but they will not be considered crazy if there is a thoughtful explanation and guidance for users. I created the wallet and it reported. outdated wallet and create another one. I don't own the private key, who is in charge of my money? If your software fails how can I get my money out if I don't have the private key?

**Comment by polymorpher** [comment] 2021-09-02 06:33
What specifically is hard to use?

The "outdated wallet" prompt is incorrect, sometimes caused by network delay. It should automatically disappear. I will fix it later.

There is no private key. The wallet is a smart contract controlled by you, and your money is stored in that contract. The user interface provides several ways for the wallet owner to recover the money: 1) restore the wallet on another device using Google Authenticator; 2) in the wallet, go to recovery tab and click recover - the money will be sent to the recovery address; 3) trigger auto-recovery by using the recovery address to send 1.0 ONE to the wallet's address.

Someone is working on user manuals and instructions. It may take some time.

**Comment by saigoncoin** [comment] 2021-09-03 03:43
ok thank you very much. I'll wait for the upcoming upgrades to have a nice experience. I'm researching and comparing new things to see if it's really worth using?I am interested in the Harmony platform, so I have to find out all that is behind it to see if it is ok, then understand if Harmony is really worth the investment. I also tried trading on the Harmony platform but feel the processing speed is quite slow (probably 15s, not 2s like what I read from them).Thank you for fixing the error of pasting the wallet address.

**Comment by polymorpher** [comment] 2021-09-23 17:19
Thanks for the feedback - though I am not sure what you meant by trading on Harmony platform. This wallet does not have much to do with trading at this point. If you meant the speed of transferring assets using 1wallet, I may be able to reduce the speed down to 5 seconds or less in the future, since right now a transfer is incurring a lot of unnecessary wait time. For issues unrelated to the wallet, I recommend having a chat with Harmony team members and people running the communities - they have some really helpful people there.

I am closing this for now - let me know if new issues come up

**Closed by polymorpher** 2021-09-23 17:19 UTC
